### PR TITLE
OAuth 2.0 JSON Web Tokens (JWT) bearer flow.

### PR DESCRIPTION
**Pull request by TuSKan**
Adding Oauth Jwt Bearer ([Salesforce doc](https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_jwt_flow.htm&type=5))

### CODE REVIEW

**Comment by k-capehart** [comment]
@TuSKan Same with this one, thanks so much! I'll review shortly.

**Comment by k-capehart** [comment]
It looks like you're committing a client_secret in `auth_test.go`. Was that on purpose?

**Comment by TuSKan** [comment]
> @TuSKan Same with this one, thanks so much! I'll review shortly.

I'm glad you like it.

> It looks like you're committing a consumerSecret in `auth_test.go`. Was that on purpose?

This was a mistake, thank you for point it out.

**Comment by k-capehart** [comment]
@TuSKan merging this into a feature branch so I can poke around a bit

**Pull request merged**
