### PR TITLE
fix: dependabot job

### PR DESCRIPTION
**Pull request by k-capehart**

### CODE REVIEW

**Comment by ccoVeille** [comment]
I'm curious, because I don't know these settings. What are they used for?

**Comment by k-capehart** [comment]
> I'm curious, because I don't know these settings. What are they used for?

@ccoVeille 
Basically dependabot should automatically check for updates to my dependencies in my `go.mod` file. If there are any updates, then it automatically opens a PR. I've used it in the past for node and python projects, and it works great.

Right now, I'm trying to add some settings so that Dependabot groups the PRs into a single PR, just to make it easier to merge them all at once.

Here's some documentation that I've been following. https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates

**Comment by ccoVeille** [comment]
> Basically dependabot should automatically check for updates to my dependencies in my go.mod file. If there are any updates, then it automatically opens a PR. I've used it in the past for node and python projects, and it works great.

I knew, but thanks for the context. Someone else might be curious about these.

> Right now, I'm trying to add some settings so that Dependabot groups the PRs into a single PR, just to make it easier to merge them all at once.

I thought only renovate not could, it's great if dependabot can too

> Here's some documentation that I've been following.

Thanks

**Comment by ccoVeille** [comment]
Let me know if it works.

The settings you used let me think it would not try to update when there is a major, because you only allowed patch and minor

**Comment by ccoVeille** [comment]
Please have a look at https://github.com/gofrs/flock/pull/72

**Comment by k-capehart** [comment]
> Please have a look at:
> 
> * [chore(ci): group dependabot PRs gofrs/flock#72](https://github.com/gofrs/flock/pull/72)
> 
> I think it's the way to do

Thanks, I'll keep that as reference. The way I implemented it seems to be working, and I was limiting to version updates so that security updates can be separated. But if I decide to combine them then I'll probably do it like this.

**Comment by k-capehart** [comment]
> Let me know if it works.
> 
> The settings you used let me think it would not try to update when there is a major, because you only allowed patch and minor

And yes, I also wanted to exclude major updates, since that might require some extra effort to rework things, depending on how many breaking changes there are.

**Comment by ccoVeille** [comment]
> > Please have a look at:
> > 
> > * [chore(ci): group dependabot PRs gofrs/flock#72](https://github.com/gofrs/flock/pull/72)
> > 
> > I think it's the way to do
> 
> Thanks, I'll keep that as reference. The way I implemented it seems to be working, and I was limiting to version updates so that security updates can be separated. But if I decide to combine them then I'll probably do it like this.

Thanks it's clearer.

**Pull request merged**
